services:
  db:
    image: postgres
    restart: always
    ports:
      - "5555:5432"
    environment:
      POSTGRES_PASSWORD: ahl@123
  test_db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: dummy
