# 1. down the application code- git clone -> DONE
# 2. go compiler should be installed on my machine - brew install -> DONE
# 3. setup docker --> DONE
# 4. install dependencies- go mod tidy -> DONE
# 5. build the app - make build --DONE
# 6. database up and migrate db- make test_db_up, make migrate_test_up.
# 7. pass env variables to test file
#     DB_HOST=db
#     DB_PASS=ahl@123
#     DB_PORT=5432
#     DB_NAME=students
#     DB_USER=postgres
#     SSL_MODE=disable
#     PORT=:8080 
# 8. run the tests - make tests

name: Go Build and Test

on:
  push:

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps: 
      - name: Clone Code
        uses: actions/checkout@v7
      - name: Setup Go
        uses: actions/setup-go@v7
        with:
          go-version-file: 'go.mod'
      - name: Setup Docker
        uses: docker/setup-docker-action@v5
      - name: Install golang-migrate CLI
        run: |
          curl -L https://github.com/golang-migrate/migrate/releases/download/v4.19.1/migrate.linux-amd64.tar.gz | tar xvz
          mv migrate /usr/local/bin
      - name: Build App
        run: make build
      - name: Start DB
        run: make test_db_up;
      - name: Run DB Migrations
        run: make migrate_test_up
      - name: Setup Session
        uses: lhotari/action-upterm@v1      

